### ISSUE TITLE
How do I move the window on Windows?

### ISSUE THREAD

**Issue by 19lmyers** [jancborchardt/hyperminimal#12]

**Comment by jancborchardt** [comment]
@19lmyers do none of the ways described at https://github.com/jancborchardt/hyperminimal#how-to-use work for you? Or also the ones in the discussion at https://github.com/jancborchardt/hyperminimal/issues/7

I don't have Windows so I can't try it out. Would be thankful if you find a solution so we can add it to the readme. :)

**Comment by jancborchardt** [comment]
@rmurai0610 @henrikdahl @net @bramkok @rastasheep @albinekb does anyone of you use Windows and can confirm if any of the ways to move the window on macOS or Ubuntu also works there? :)

**Comment by gavanitrate** [comment]
@jancborchardt 
None of the other OS's methods seem to work on Windows 10.
Best way I could find was Alt+Space+M (Opens the Window Menu and then chooses the **M**ove option). Then arrow keys for movement; after pressing a key atleast once, the window will then follow the mouse cursor.
![2017-06-17_01-19-12](https://user-images.githubusercontent.com/8264198/27232934-23f7d514-52fb-11e7-9313-ae9fba78389e.gif)
Works okay but sometimes the UP arrow key will trigger as input in the terminal and roll through your history.
Would be great if someone could find a better method.

**Comment by jancborchardt** [comment]
@gavanitrate cool! That will help a lot already, mind opening a Pull Request with adding that hint to the Readme in the style like it is for macOS and Ubuntu? :)

**Comment by jancborchardt** [comment]
Fixed thanks to @gavanitrate through https://github.com/jancborchardt/hyperminimal/pull/13 :)

**Comment by KHZ-INTL** [comment]
I have used cmder terminal emulator, I have it configured to hide the title bar and other distracting gui elements. I use Ctrl + Alt + click + Mouse to move the window. I think you would be able to find something in their source code?


![Animation](https://user-images.githubusercontent.com/9879109/34746147-e48ea598-f5e2-11e7-8f73-9df7c03a8fbb.gif)


Cmder github page:
https://github.com/cmderdev/cmder

**Comment by jancborchardt** [comment]
@KHZ-INTL does the shortcut not work for Hyper?

Because if not, I think it will only work if implemented in Hyper directly. Hence an issue should be opened at https://github.com/zeit/hyper/issues (I searched and no related one seems to exist). :)

**Comment by kvnloo** [comment]
@KHZ-INTL This is unrelated to the issue but I was wondering what software you use for that menu bar, it looks amazing and I'd like to get it on my system.

**Comment by raulf2012** [comment]
My solution is to use an Autohotkey script that allows a window to be dragged by pressing alt+left_mouse_click_and_hold on a window.

It works for all windows (not just Hyper), the only disadvantage is that it can severely warp window size when transitioning between different monitors.


See the link below for instructions on how to install Autohotkey and/or the specific window moving script.
Autohotkey Script:
https://www.howtogeek.com/howto/windows-vista/get-the-linux-altwindow-drag-functionality-in-windows/

![autohotkey_move_window](https://user-images.githubusercontent.com/28916036/40272800-a81f8e88-5b68-11e8-9caa-76b9354d1bce.gif)

**Comment by jancborchardt** [comment]
@raulf2012 cool! Want to open a pull request to add a quick instruction sentence about that in the readme? :)

**Comment by mnxn** [comment]
Same thing also exists in https://github.com/stefansundin/altdrag with some added functionality.
