### ISSUE TITLE
Does not work with Hyper 1.4.1

### ISSUE THREAD

**Issue by jessemillar** [jancborchardt/hyperminimal#14]
I just updated a few minutes ago and the nasty header bar is back. Gotta love those updates, huh?

**Comment by jessemillar** [comment]
Fixed by Hyper 1.4.2 (https://github.com/zeit/hyper/releases/tag/1.4.2).

**Comment by jancborchardt** [comment]
@jessemillar thanks for reporting and also updating that it works again! :) Happy you like it!

**Comment by jessemillar** [comment]
Can't live without it! I love my minimal terminal!
