### ISSUE TITLE
Titlebar still occupies space after hiding

### ISSUE THREAD

**Issue by satya164** [jancborchardt/hyperminimal#20]
After hiding the title bar, there's still empty space at the top. Which is useful because you can still grab the window to move around, but it covers any text below it, which means you cannot select the text or do things such as alt+click.

Here is a screenshot which demonstrates the issue:

<img width="608" alt="screenshot 2018-07-20 at 1 32 14 pm" src="https://user-images.githubusercontent.com/1174278/43000348-57d1ea7c-8c21-11e8-9051-5f16112c827a.png">

For now, I added the following CSS in my config to remove the extra space so that it doesn't cover any text, but still allows me to move the window around (14px is my top padding):

```css
.tabs_nav {
  height: auto;
  min-height: 14px;
}
```

But it would be nice if this was done automatically.

**Comment by jancborchardt** [comment]
@satya164 does this also occur on a new installation with no other customization? If so, could you submit a pull request to fix it? :)

No need to leave the extra drag space since there's other methods for that as specified in the readme.

**Comment by satya164** [comment]
I have the following plugins:

```
  plugins: [
    "hypercwd",
    "hyperlinks",
    "hyper-search",
    "hyperminimal",
    "hyper-tabs-enhanced",
    "hyper-statusline",
    "hyperterm-palenight"
  ],
```

Except that I have only customized few things in the config like changing the cursor, which I believe shouldn't affect it. I'll try after removing all plugins.

> If so, could you submit a pull request to fix it? :)

Will try to :)

> No need to leave the extra drag space since there's other methods for that as specified in the readme.

Yeah, but it's still nice to drag it using only mouse/touchpad since I'm a heavy touchpad user. But as long as I can override the behavior, I don't mind if it isn't in default styles :D

**Comment by satya164** [comment]
Confirmed that it still happens when I remove all other plugins. Will send a PR.
