### ISSUE TITLE
How to move window without header? 

### ISSUE THREAD

**Issue by Alex0007** [jancborchardt/hyperminimal#7]
I'm on Elementary OS. Plugin is awesome, but sometimes i need to move window. Maybe some hacks exist to make it movable?

**Comment by jancborchardt** [comment]
@Alex0007 it should be possible by holding down the Super / Windows key and then moving it with the cursor (you can click anywhere). Works here on Ubuntu + GNOME Shell, let me know if it works on Elementary too. :)

**Comment by jancborchardt** [comment]
Also clarified it in the readme now: https://github.com/jancborchardt/hyperminimal/blob/master/readme.md

Thanks for the notice! :) Hope hyperminimal works nicely for you

**Comment by Alex0007** [comment]
Thanks for this info! Works well on Elementary too

**Comment by aersoares81** [comment]
Hi, moving holding super is not working for me on Ubuntu 16.04. My plugins are 'hyperline', 'hyper-blink', 'hyper-solarized-dark', 'hyperlinks', 'hyper-tab-icons', 'hypercwd', 'hyperminimal'.

I can resize the window, but not move it.

**Comment by jancborchardt** [comment]
@aersoares81 I am also on Ubuntu 16.04, with GNOME (although I don’t think it will make a difference). Moving windows via holding the Super key should also work with the file manager, browser etc – I haven’t seen it _not_ work. Can you check if it works for you elsewhere?
Otherwise maybe try disabling all extensions quickly to test? :) Thank you!

**Comment by aersoares81** [comment]
@jancborchardt I think it's Unity that doesn't allow me to do that for any program at all, not a particular bug with Hyper. Sorry for that!

**Comment by jancborchardt** [comment]
@aersoares81 ah no worries. Sorry about that not working. :( If you find a solution please add it to the readme :) https://github.com/jancborchardt/hyperminimal#how-to-use

Don’t hesitate to report other issues! Hope the extension works fine for you otherwise.
